### ISSUE TITLE
Foodcritic FC070 rule fails

### ISSUE THREAD

**Issue by tortila** [aspyatkin/yarn-cookbook#3]
Hi,

I spotted that [Foodcritic FC070](http://www.foodcritic.io/#FC070) rule fails because metadata.rb contains `rhel` in list of supported platforms. I see that the rule is quite new, added on April 10th, 2017. Please change the metadata file so that Foodcritic rules are passing.

**Comment by aspyatkin** [comment]
@tortila Thank you for pointing this out! I've updated the file and bumped the cookbook version to `0.3.1`.
